// Generated by https://quicktype.io

export interface TopLevel {
  id:              number;
  href:            string;
  title:           string;
  date:            string;
  author:          string;
  category:        string;
  "category-link": string;
  summary:         string;
}
